AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  stockApplication

  Sample SAM Template for stockApplication

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: java8
    Environment:
      Variables:
        dbUrl: "jdbc:mysql://database-2-instance-1.cbscbcwxhk49.us-east-2.rds.amazonaws.com"
        userName: "admin"
        password: "password"

Resources:
  GetAllStocksHandlerFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: stockApplication
      Handler: com.stock.lambda.GetAllStocksHandler::handleRequest
      MemorySize: 512
      Events:
        GetStock:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /stock/get/{companyCode}/{startDate}/{endDate}
            Method: get
  CreateStockHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: stockApplication
      Handler: com.stock.lambda.CreateStockHandler::handleRequest
      MemorySize: 512
      Events:
        CreateStock:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /stock/create
            Method: post   

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  GetAllStocksFunction:
    Description: "get stocks Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  GetAllStocksApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Stock Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/stock/get/{companyCode}/{startDate}/{endDate}"
  GetAllStocksHandlerFunction:
    Description: "Get Stock Function ARN"
    Value: !GetAtt GetAllStocksHandlerFunction.Arn
  CreateStockFunction:
    Description: "create stocks Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  CreateStockApi:
    Description: "API Gateway endpoint URL for Prod stage for Create Stock Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod//stock/create"
  CreateStockHandlerFunction:
    Description: "Create Stock Function ARN"
    Value: !GetAtt CreateStockHandlerFunction.Arn
